### ISSUE TITLE
Allow changing karma of slack users

### ISSUE THREAD

**Issue by AlexanderPruss** [AlexanderPruss/KarmaBot#6]
If you try to change the karma of a slack user, e.g.

`@karmabot @AlexPruss++`

You'll end up incrementing the karma of a random string that represents `@AlexPruss` in the Slack backend. Maybe we can figure out how to translate this back into a string

**Comment by lukasz-madej** [comment]
@AlexanderPruss 
https://github.com/AlexanderPruss/KarmaBot/pull/8

**Comment by AlexanderPruss** [comment]
Turns out we misunderstood why this wasn't working; I adjusted Lukasz's PR with #9
